name = "CandidatePackTools"
uuid = "79692de3-e45f-4abf-8d4a-e8cb837271f2"
authors = ["David AW Barton"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
